### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by vporoshok** [tubignat/ElmaTestTask#1]
1. Горутин сейчас запуститься столько, сколько будет заданий, после чего они будут ждать освобождения семафора. Проблема в том, что каждая горутина занимает порядка 4 КБ памяти без учёта локальных переменных, поэтому хорошо бы не стартовать их заранее.
2. Ошибка пишется в StdOut, желательно её писать в StdErr.

**Comment by tubignat** [comment]
1. Как вариант можно ждать семафора до того, как создавать горутину. Тогда вычитывание слеующих строк из std тоже будет ждать семафора, но это, кажется, не критично. Если такой вариант - ок, то сделаю так. Альтернативно можно шедулить задачи в очередь и в отдельном потоке ждать семафор и запускать их, но это немного оверхед

**Comment by vporoshok** [comment]
первый вариант подходит отлично

**Comment by tubignat** [comment]
https://github.com/tubignat/ElmaTestTask/commit/e51b0568f1ed36dc7fdcdae64e427e7923b45fbd

**Comment by vporoshok** [comment]
Спасибо!
